config/routes.rb
Rails.application.routes.draw do
  root 'loans#new'
  resources :loans
  resources :borrowers do
    member do 
      get :history
    end
  end
  resources :books do
    member do 
      get :history
    end
  end
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  code       :string(255)
#  title      :string(255)
#  author     :string(255)
#  returned   :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  validates_presence_of :code
  validates_uniqueness_of :code

  has_many :loans, dependent: :destroy
  has_one :outstanding_loan, -> { where returned: false }, class_name: :Loan
  has_one :borrower, through: :outstanding_loan

  scope :available, -> {
    where returned: true
  }

  after_initialize do
    self.code ||= begin
      if (last_code = Book.last.try :code) && (match = /\d+$/.match(last_code))
        digits = match.to_s
        "#{last_code[0...(0 - digits.size)]}#{(digits.to_i + 1).to_s.rjust digits.size, '0'}"
      end
    end
  end

  def to_s
    "#{self.code}: #{self.title}"
  end
end

app/models/borrower.rb
# == Schema Information
#
# Table name: borrowers
#
#  id         :integer          not null, primary key
#  code       :string(255)
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Borrower < ActiveRecord::Base
  validates_presence_of :code
  validates_uniqueness_of :code
  
  has_many :loans, dependent: :destroy

  after_initialize do
    self.code ||= begin
      if (last_code = Borrower.last.try :code) && (match = /\d+$/.match(last_code))
        digits = match.to_s
        "#{last_code[0...(0 - digits.size)]}#{(digits.to_i + 1).to_s.rjust digits.size, '0'}"
      end
    end
  end

  def to_s
    "#{self.code}: #{self.name}"
  end
end

app/models/loan.rb
# == Schema Information
#
# Table name: loans
#
#  id          :integer          not null, primary key
#  borrower_id :integer
#  book_id     :integer
#  start       :date
#  end         :date
#  returned    :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Loan < ActiveRecord::Base
  belongs_to :book
  belongs_to :borrower

  validates_presence_of :book_id, :borrower_id, :start, :end

  after_initialize do
    self.start ||= Date.today
    self.end ||= 3.weeks.from_now
    self.returned ||= false
  end


  after_save do
    if self.returned_changed?
      self.book.update_attributes! returned: self.returned
    end
  end

  after_destroy do
    self.book.update_attributes! returned: true unless self.returned
  end

  validate :book_id do
    if self.new_record? && self.book
      unless self.book.returned
        self.errors.add :book_id, "is not available at this moment."
      end
    end
  end
  validate :end do
    unless self.end > self.start
      self.errors.add :end, "must be after a date after #{self.start}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  code       :string(255)
#  title      :string(255)
#  author     :string(255)
#  returned   :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :history]

  # GET /books
  def index
    like_exp = "%#{params[:keyword]}%"
    @books = Book.where("code like ? or title like ? or author like ?", like_exp, like_exp, like_exp)
  end

  # GET /books/1
  def show
    @loans = @book.loans.where(returned: false)
  end
  def history
    @loans = @book.loans.where(returned: true)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:code, :title, :author)
    end
end

app/controllers/borrowers_controller.rb
# == Schema Information
#
# Table name: borrowers
#
#  id         :integer          not null, primary key
#  code       :string(255)
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BorrowersController < ApplicationController
  before_action :set_borrower, only: [:show, :edit, :update, :destroy, :history]

  # GET /borrowers
  def index
    like_exp = "%#{params[:keyword]}%"
    @borrowers = Borrower.where("code like ? or name like ?", like_exp, like_exp)
  end

  # GET /borrowers/1
  def show
    @loans = @borrower.loans.where(returned: false)
    @loan = Loan.new borrower: @borrower
  end
  def history
    @loans = @borrower.loans.where(returned: true)
  end


  # GET /borrowers/new
  def new
    @borrower = Borrower.new
  end

  # GET /borrowers/1/edit
  def edit
  end

  # POST /borrowers
  def create
    @borrower = Borrower.new(borrower_params)

    if @borrower.save
      redirect_to @borrower, notice: 'Borrower was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /borrowers/1
  def update
    if @borrower.update(borrower_params)
      redirect_to @borrower, notice: 'Borrower was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /borrowers/1
  def destroy
    @borrower.destroy
    redirect_to borrowers_url, notice: 'Borrower was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrower
      @borrower = Borrower.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def borrower_params
      params.require(:borrower).permit(:code, :name)
    end
end

app/controllers/loans_controller.rb
# == Schema Information
#
# Table name: loans
#
#  id          :integer          not null, primary key
#  borrower_id :integer
#  book_id     :integer
#  start       :date
#  end         :date
#  returned    :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # POST /loans
  def create
    @loan = Loan.new(loan_params)
    respond_to do |format|
      format.html{
        if @loan.save
          redirect_to @loan.borrower, notice: 'Loan was successfully created.'
        else
          render :new
        end
      }
      format.js{
        if @loan.save
          redirect_via_turbolinks_to @loan.borrower, notice: 'Loan was successfully created.'
        else
          @message = "Unable to submit loan, because: #{@loan.errors.full_messages.to_sentence}"
          render 'error'
        end
      }
    end
  end

  # PATCH/PUT /loans/1
  def update
    if @loan.update(loan_params)
      @message = 'Loan was successfully updated.'
      render 'success'
    else
      @message = "Unable to submit loan, because: #{@loan.errors.full_messages.to_sentence}"
      render 'error'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def loan_params
      params.require(:loan).permit(:borrower_id, :book_id, :end, :returned)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def btn_to text, url,options={}, &block
    options[:style] ||= 'default'
    options[:class] ||= ''
    options[:class] += " btn btn-#{options[:style]}"
    link_to text, url, options, &block
  end
  ['default', 'primary', 'danger', 'info', 'success', 'warning'].each do |style|
    define_method "#{style}_btn_to" do |text, url, options={}, &block|
      options[:style] = style
      btn_to text, url, options, &block
    end
  end
end

app/views/books/_form.html.haml
= bootstrap_form_for @book do |f|
  = f.text_field :code
  = f.text_field :title, autocomplete: :off
  = f.text_field :author
  = f.submit

app/views/books/edit.html.haml
= panel heading: 'Edit Book' do
  .panel-body
    = render partial: 'form', locals: { form: @book }

app/views/books/history.html.haml
= panel heading: "Borrowers of #{@book}" do
  .panel-body
    = nav do
      = link_to 'Outstanding', @book
      = link_to 'History', history_book_path(@book)
    .table-responsive
      = table_for @loans, table_html: { class: :table } do |t|
        = t.column :borrower
        = t.column :start
        = t.column :end

app/views/books/index.html.haml
= panel heading: 'Books' do
  .panel-body
    = bootstrap_form_tag method: :get do |f|
      = f.text_field :keyword, value: params[:keyword]
      = f.submit 'Search'
      = info_btn_to 'New Book', new_book_path
    .table-responsive
      = table_for @books, table_html: { class: :table } do |t|
        = t.column :code
        = t.column :title
        = t.column :author
        = t.column :borrower
        = t.column data: 'View Borrowers', link_method: :get
        = t.column data: 'Edit', link_action: :edit
        = t.column data: 'Delete', link_method: :delete

app/views/books/new.html.haml
= panel heading: 'New Book' do
  .panel-body
    = render partial: 'form', locals: { form: @book }

app/views/books/show.html.haml
= panel heading: "Borrowers of #{@book}" do
  .panel-body
    = nav do
      = link_to 'Outstanding', @book
      = link_to 'History', history_book_path(@book)
    .table-responsive
      = table_for @loans, table_html: { class: :table } do |t|
        = t.column :borrower
        = t.column :start
        = t.column :end do |loan|
          = bootstrap_form_for loan, layout: :inline, remote: true do |f|
            = f.date_field :end
            = f.submit
        = t.column do |loan|
          = btn_to 'Return', loan_path(loan, 'loan[returned]': true), method: :put, remote: true

app/views/borrowers/_form.html.haml
= bootstrap_form_for @borrower do |f|
  = f.text_field :code
  = f.text_field :name, autocomplete: :off
  = f.submit

app/views/borrowers/edit.html.haml
= panel heading: 'Edit Borrower' do
  .panel-body
    = render partial: 'form', locals: { form: @borrower }

app/views/borrowers/history.html.haml
= panel heading: "Borrowings of #{@borrower}" do
  .panel-body
    = nav do
      = link_to 'Outstanding', @borrower
      = link_to 'History', history_borrower_path(@borrower)
    .table-responsive
      = table_for @loans, table_html: { class: :table } do |t|
        = t.column :book
        = t.column :start
        = t.column :end

app/views/borrowers/index.html.haml
= panel heading: 'Borrowers' do
  .panel-body
    = bootstrap_form_tag method: :get do |f|
      = f.text_field :keyword, value: params[:keyword]
      = f.submit 'Search'
      = info_btn_to 'New Borrower', new_borrower_path
    .table-responsive
      = table_for @borrowers, table_html: { class: :table } do |t|
        = t.column :code
        = t.column :name
        = t.column data: 'View Borrowings', link_method: :get
        = t.column data: 'Edit', link_action: :edit
        = t.column data: 'Delete', link_method: :delete

app/views/borrowers/new.html.haml
= panel heading: 'New Borrower' do
  .panel-body
    = render partial: 'form', locals: { form: @borrower }

app/views/borrowers/show.html.haml
= panel heading: "Borrowings of #{@borrower}" do
  .panel-body
    = nav do
      = link_to 'Outstanding', @borrower
      = link_to 'History', history_borrower_path(@borrower)
    .table-responsive
      = table_for @loans, table_html: { class: :table } do |t|
        = t.column :book
        = t.column :start
        = t.column :end do |loan|
          = bootstrap_form_for loan, layout: :inline, remote: true do |f|
            = f.date_field :end
            = f.submit
        = t.column do |loan|
          = btn_to 'Return', loan_path(loan, 'loan[returned]': true), method: :put, remote: true
    = panel heading: "New Borrowing for #{@borrower}" do
      .panel-body
        = bootstrap_form_for @loan, remote: true do |f|
          = f.hidden_field :borrower_id
          = f.collection_select :book_id, Book.available, :id, :to_s
          = f.static_control :start
          = f.date_field :end
          = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Library App
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}
    %meta{:content => "black", :name => "apple-mobile-web-app-status-bar-style"}
    %meta{:content => "telephone=no", :name => "format-detection"}
    %meta{:content => "width=device-width,initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{ style: 'padding-top: 70px;' }
    = navbar fixed: :top, container: 'fluid' do
      = navbar_header brand: '<span class="fa fa-cog"></span>Library App', brand_link: root_path
      = navbar_collapse do
        = navbar_group do
          = navbar_item root_path do
            %span.fa.fa-home
            Home
          = navbar_item books_path do
            %span.fa.fa-book
            Books
          = navbar_item borrowers_path do
            %span.fa.fa-users
            Users
    .container-fluid
      - flash.each do |type, message|
        .alert{class: { alert: 'alert-danger', notice: 'alert-success' }[type.to_sym]}
          = message
      = yield
      %p.small
        %a{ href: 'https://github.com/layerssss/library_app' } 
          %span.fa.fa-github
          layerssss/library_app

app/views/loans/new.html.haml
= panel heading: 'New Loan' do
  .panel-body
    = bootstrap_form_for @loan do |f|
      = f.collection_select :borrower_id, Borrower.all, :id, :to_s
      = f.collection_select :book_id, Book.available, :id, :to_s
      = f.static_control :start
      = f.date_field :end
      = f.submit